export const retroPromptKeys = [
  "GIRL_TEMPLATE_RETRO",
  "SINGLE_BOY_RETRO",
  "COUPLE_SCOOTER",
  "GIRL_CAR_TEMPLATE",
  "COUPLE_BULLET",
  "VIDEO_RENTAL_90S",
  "GIRL_CAMERA",
  "BOY_CAR_RETRO",
  "RETRO_FAMILY",
] as const;

export type RetroPromptKey = (typeof retroPromptKeys)[number];

export const retroTemplateDefinitions = [
  {
    id: "retro-girl-template-001",
    name: "80s Retro Girl",
    description: "Colorful 1980s fashion with an authentic vintage-photo finish.",
    previewImage: "/templates/retro-girl-template-v1.webp",
    relationshipId: "retro-single",
    identityMode: "RETRO_SINGLE",
    promptKey: "GIRL_TEMPLATE_RETRO",
    sortOrder: 1,
  },
  {
    id: "retro-single-boy-001",
    name: "80s Retro Boy",
    description: "A cinematic 1980s magazine portrait with nostalgic film color.",
    previewImage: "/templates/retro-single-boy-v1.webp",
    relationshipId: "retro-single",
    identityMode: "RETRO_SINGLE",
    promptKey: "SINGLE_BOY_RETRO",
    sortOrder: 2,
  },
  {
    id: "retro-couple-scooter-001",
    name: "Couple Scooter",
    description: "A charming 1980s South Indian couple portrait with a vintage scooter.",
    previewImage: "/templates/retro-couple-scooter-v1.webp",
    relationshipId: "retro-couple",
    identityMode: "RETRO_COUPLE",
    promptKey: "COUPLE_SCOOTER",
    sortOrder: 3,
  },
  {
    id: "retro-girl-car-001",
    name: "Retro Girl by Car",
    description: "A faded 1986 hill-road portrait beside a classic red car.",
    previewImage: "/templates/retro-girl-car-v1.webp",
    relationshipId: "retro-single",
    identityMode: "RETRO_SINGLE",
    promptKey: "GIRL_CAR_TEMPLATE",
    sortOrder: 4,
  },
  {
    id: "retro-couple-bullet-001",
    name: "Couple Bullet",
    description: "A playful 1980s couple fashion portrait with a vintage motorcycle.",
    previewImage: "/templates/retro-couple-bullet-v1.webp",
    relationshipId: "retro-couple",
    identityMode: "RETRO_COUPLE",
    promptKey: "COUPLE_BULLET",
    sortOrder: 5,
  },
  {
    id: "retro-video-rental-001",
    name: "90s Video Rental",
    description: "An expired-film portrait inside a nostalgic video rental shop.",
    previewImage: "/templates/retro-video-rental-v1.webp",
    relationshipId: "retro-single",
    identityMode: "RETRO_SINGLE",
    promptKey: "VIDEO_RENTAL_90S",
    sortOrder: 6,
  },
  {
    id: "retro-girl-camera-001",
    name: "Retro Girl with Camera",
    description: "A folded 1985 film print with a classic SLR camera.",
    previewImage: "/templates/retro-girl-camera-v1.webp",
    relationshipId: "retro-single",
    identityMode: "RETRO_SINGLE",
    promptKey: "GIRL_CAMERA",
    sortOrder: 7,
  },
  {
    id: "retro-boy-car-001",
    name: "Retro Boy by Car",
    description: "A warm 1980s fashion portrait beside a classic automobile.",
    previewImage: "/templates/retro-boy-car-v1.webp",
    relationshipId: "retro-single",
    identityMode: "RETRO_SINGLE",
    promptKey: "BOY_CAR_RETRO",
    sortOrder: 8,
  },
  {
    id: "retro-family-001",
    name: "Retro Family",
    description: "A warm 1980s family portrait with father, mother, and toddler.",
    previewImage: "/templates/retro-family-v1.webp",
    relationshipId: "retro-family",
    identityMode: "RETRO_FAMILY",
    promptKey: "RETRO_FAMILY",
    sortOrder: 9,
  },
] as const;
